KostenVoorEenBaan: 2500
KrijgItemsBijBaanSelect: true
PrefixEnabled: true
Messages:
  VeranderenVanEenBaan: '&4Let op! &cHet veranderen van beroep kost &4€ <Bedrag>,-&c.'
  InventoryTitle: '&3Kies een &bberoep&3!'
  ItemName: '&3<Beroep>'
  ItemLore: '&3Kies het beroep &b<Beroep>'
  BeroepNodig: '&4ERROR: &cHiervoor heb je het beroep &4<Beroep> &cnodig!'
  ToolNodig: '&4ERROR: &cHiervoor heb je een &4<Tool> &cnodig!'
  TarweNietVolgroeid: '&4ERROR: &cDeze tarwe is niet volgroeid!'
  BietenNietVolgroeid: '&4ERROR: &cDeze bieten zijn niet volgroeid!'
  WortelNietVolgroeid: '&4ERROR: &cDeze wortel is niet volgroeid!'
  AardappelNietVolgroeid: '&4ERROR: &cDeze aardappel is niet volgroeid!'
  TeWeinigGeld: '&4ERROR: &cOm van baan te veranderen heb je &4€ <Bedrag> &cnodig!'
  GeldBetaald: '&3Gelukt! Wij hebben jou &b€ <Bedrag> &3betaald voor jouw opgehaalde
    spullen!'
  BaanVeranderd: '&3Jouw baan is succesvol veranderd naar &b<Baan>&3.'
  GeenRegion: '&4ERROR: &cDeze region moet de tag &4''<Tag>'' &chebben.'
  Creative: '&3Omdat jij in &bCREATIVE &3zit heb jij een MinetopiaFarms bypass..'
  NPC:
    Name: '&6Verkooppunt'
    Skin:
      Name: MrWouter
      UUID: 836ce767-0e25-45a0-8012-fa1864d2b6aa
scheduler:
  cropgrow: 120
  perstatetime: 120
  miner:
    COAL_ORE: 2400
    DIAMOND_ORE: 2400
    EMERALD_ORE: 2400
    GOLD_ORE: 2400
    IRON_ORE: 2400
    LAPIS_ORE: 2400
    REDSTONE_ORE: 2400
ItemsBijBaanSelect:
  Boer:
    - DIAMOND_HOE
  Mijnwerker:
    - DIAMOND_PICKAXE
  Houthakker:
    - DIAMOND_AXE
Banen:
  Mijnwerker:
    Enabled: true
    Item: DIAMOND_PICKAXE
  Boer:
    Enabled: true
    Item: DIAMOND_HOE
  Houthakker:
    Enabled: true
    Item: DIAMOND_AXE
TerugverkoopPrijs:
  Mijnwerker:
    COAL_ORE: 10
    IRON_ORE: 25
    EMERALD_ORE: 30
    GOLD_ORE: 25
    LAPIS_ORE: 35
    REDSTONE_ORE: 25
    DIAMOND_ORE: 80
  Boer:
    BEETROOTS: 35
    WHEAT: 10
    MELON: 30
    PUMPKIN: 30
    CARROTS: 20
    POTATOES: 20
  Houthakker: 25
CommandsUitvoerenBijBaanWissel:
  Boer:
    - Typ hier jouw commands
  Houthakker:
    - Typ hier jouw commands
  Mijnwerker:
    - Typ hier jouw commands
