name: MinetopiaFarms
version: 1.3
author: MrWouter
description: Farms en Mines
main: nl.wouter.minetopiafarms.Main
loadbefore: [WorldGuard]
commands:
     kies:
     minetopiafarms:
        aliases: [mtfarms, farms]