name: MinetopiaFarms
version: 2.5
api-version: 1.13
author: MrWouter
description: Farms en Mines
main: nl.wouter.minetopiafarms.Main
loadbefore: [WorldGuard]
depend: [Citizens, WorldGuard, WorldEdit, Vault, MinetopiaSDB]
commands:
     kies:
     minetopiafarms:
        aliases: [mtfarms, farms]